/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param date 
 * @param slot 
 * @param secondName 
 * @param secondTg 
 */


data class FutureMeet (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "date")
    val date: java.time.LocalDate? = null,

    @Json(name = "slot")
    val slot: kotlin.Int? = null,

    @Json(name = "secondName")
    val secondName: kotlin.String? = null,

    @Json(name = "secondTg")
    val secondTg: kotlin.String? = null

) {


}

