/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param date 
 * @param timeOfDate 
 */


data class ScheduleSlot (

    @Json(name = "date")
    val date: java.time.LocalDate? = null,

    @Json(name = "timeOfDate")
    val timeOfDate: kotlin.Int? = null

) {


}

