/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ScheduleSlot

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param toDelete 
 * @param toAdd 
 */


data class UserScheduleChange (

    @Json(name = "toDelete")
    val toDelete: kotlin.collections.List<ScheduleSlot>? = null,

    @Json(name = "toAdd")
    val toAdd: kotlin.collections.List<ScheduleSlot>? = null

) {


}

