openapi: 3.1.0
info:
  title: RandomCoffee
  version: 0.2.0

tags:
  - name: interests
  - name: schedule
  - name: meet
  - name: user
  - name: auth


paths:
  /interests:
    get:
      tags:
        - interests
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Interests'

  /interests/{userId}:
    get:
      tags:
        - interests
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInterests'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    post:
      tags:
        - interests
      security:
        - bearerAuth: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInterests'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInterests'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /schedule/{userId}:
    get:
      tags:
        - schedule
      security:
        - bearerAuth: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: start_date
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSchedule'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    post:
      tags:
        - schedule
      security:
        - bearerAuth: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: start_date
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          required: false
          schema:
            type: string
            format: date
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserScheduleChange'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSchedule'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /user/{userId}:
    get:
      tags:
        - user
      security:
        - bearerAuth: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    patch:
      tags:
        - user
      security:
        - bearerAuth: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
      responses:
        '200':
          description: Successful change
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /register:
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
      responses:
        '200':
          description: Successful registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /login:
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /refresh:
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: Successful refresh
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /meet/history/{userId}:
    get:
      tags:
        - meet
      security:
        - bearerAuth: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: start_date
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoryMeets'
        '401':
          $ref: '#/components/responses/UnauthorizedError'


  /meet/future/{userId}:
    get:
      tags:
        - meet
      security:
        - bearerAuth: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FutureMeets'
        '401':
          $ref: '#/components/responses/UnauthorizedError'


  /meet/approve/{userId}/{meetId}:
    post:
      tags:
        - meet
      security:
        - bearerAuth: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
        - name: meetId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '401':
          $ref: '#/components/responses/UnauthorizedError'







components:
  schemas:
    HistoryMeets:
      type: array
      items:
        $ref: '#/components/schemas/HistoryMeet'

    HistoryMeet:
      type: object
      properties:
        date:
          type: string
          format: date
        secondName:
          type: string
        secondTgHandle:
          type: string

    FutureMeets:
      type: object
      properties:
        notApproved:
          type: array
          items:
            $ref: '#/components/schemas/HistoryMeet'
        approved:
          type: array
          items:
            $ref: '#/components/schemas/FutureMeet'

    FutureMeet:
      type: object
      properties:
        id:
          type: integer
        date:
          type: string
          format: date
        slot:
          $ref: '#/components/schemas/TimeSlot'
        secondName:
          type: string
        secondTg:
          type: string

    FutureMeetNotApproved:
      type: object
      properties:
        id:
          type: integer
        date:
          type: string
          format: date
        slot:
          $ref: '#/components/schemas/TimeSlot'

    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
          format: JWT
        refreshToken:
          type: string
          format: JWT

    UserRegister:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
        tg_handle:
          type: string
        display_name:
          type: string
        tos_accept:
          type: boolean

    User:
      type: object
      properties:
        login:
          type: string
        tg_handle:
          type: string
        display_name:
          type: string

    Interest:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

    InterestGroup:
      type: object
      properties:
        name:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Interest'

    UserInterests:
      type: array
      items:
        $ref: '#/components/schemas/Interest'

    Interests:
      type: array
      items:
        $ref: '#/components/schemas/InterestGroup'

    ScheduleSlot:
      type: object
      properties:
        date:
          type: string
          format: date
        timeOfDate:
          $ref: '#/components/schemas/TimeSlot'

    TimeSlot:
      type: integer
      format: int32
      description: morning - 1, day - 2, evening - 4, bitmask

    UserSchedule:
      type: array
      items:
        $ref: '#/components/schemas/ScheduleSlot'

    UserScheduleChange:
      type: object
      properties:
        toDelete:
          type: array
          items:
            $ref: '#/components/schemas/ScheduleSlot'
        toAdd:
          type: array
          items:
            $ref: '#/components/schemas/ScheduleSlot'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
