/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.AuthApi
import org.openapitools.client.models.LoginDetails
import org.openapitools.client.models.UserRegister

class AuthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthApi
        //val apiInstance = AuthApi()

        // to test loginPost
        should("test loginPost") {
            // uncomment below to test loginPost
            //val loginDetails : LoginDetails =  // LoginDetails | 
            //val result : kotlin.String = apiInstance.loginPost(loginDetails)
            //result shouldBe ("TODO")
        }

        // to test registerPost
        should("test registerPost") {
            // uncomment below to test registerPost
            //val userRegister : UserRegister =  // UserRegister | 
            //val result : kotlin.String = apiInstance.registerPost(userRegister)
            //result shouldBe ("TODO")
        }

    }
}
