/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.InterestsApi
import org.openapitools.client.models.Interest
import org.openapitools.client.models.InterestGroup

class InterestsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InterestsApi
        //val apiInstance = InterestsApi()

        // to test interestsGet
        should("test interestsGet") {
            // uncomment below to test interestsGet
            //val result : kotlin.collections.List<InterestGroup> = apiInstance.interestsGet()
            //result shouldBe ("TODO")
        }

        // to test interestsUserIdGet
        should("test interestsUserIdGet") {
            // uncomment below to test interestsUserIdGet
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val result : kotlin.collections.List<Interest> = apiInstance.interestsUserIdGet(userId)
            //result shouldBe ("TODO")
        }

        // to test interestsUserIdPost
        should("test interestsUserIdPost") {
            // uncomment below to test interestsUserIdPost
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val interest : kotlin.collections.List<Interest> =  // kotlin.collections.List<Interest> | 
            //val result : kotlin.collections.List<Interest> = apiInstance.interestsUserIdPost(userId, interest)
            //result shouldBe ("TODO")
        }

    }
}
