/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.MeetApi
import org.openapitools.client.models.FutureMeets
import org.openapitools.client.models.HistoryMeet

class MeetApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MeetApi
        //val apiInstance = MeetApi()

        // to test meetApproveUserIdMeetIdPost
        should("test meetApproveUserIdMeetIdPost") {
            // uncomment below to test meetApproveUserIdMeetIdPost
            //val userId : kotlin.Int = 56 // kotlin.Int | 
            //val meetId : kotlin.Int = 56 // kotlin.Int | 
            //apiInstance.meetApproveUserIdMeetIdPost(userId, meetId)
        }

        // to test meetFutureUserIdGet
        should("test meetFutureUserIdGet") {
            // uncomment below to test meetFutureUserIdGet
            //val userId : kotlin.Int = 56 // kotlin.Int | 
            //val result : FutureMeets = apiInstance.meetFutureUserIdGet(userId)
            //result shouldBe ("TODO")
        }

        // to test meetHistoryUserIdGet
        should("test meetHistoryUserIdGet") {
            // uncomment below to test meetHistoryUserIdGet
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | 
            //val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | 
            //val result : kotlin.collections.List<HistoryMeet> = apiInstance.meetHistoryUserIdGet(userId, startDate, endDate)
            //result shouldBe ("TODO")
        }

    }
}
