/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ScheduleApi
import org.openapitools.client.models.ScheduleSlot
import org.openapitools.client.models.UserScheduleChange

class ScheduleApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ScheduleApi
        //val apiInstance = ScheduleApi()

        // to test scheduleUserIdGet
        should("test scheduleUserIdGet") {
            // uncomment below to test scheduleUserIdGet
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | 
            //val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | 
            //val result : kotlin.collections.List<ScheduleSlot> = apiInstance.scheduleUserIdGet(userId, startDate, endDate)
            //result shouldBe ("TODO")
        }

        // to test scheduleUserIdPost
        should("test scheduleUserIdPost") {
            // uncomment below to test scheduleUserIdPost
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | 
            //val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | 
            //val userScheduleChange : UserScheduleChange =  // UserScheduleChange | 
            //val result : kotlin.collections.List<ScheduleSlot> = apiInstance.scheduleUserIdPost(userId, startDate, endDate, userScheduleChange)
            //result shouldBe ("TODO")
        }

    }
}
