/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.UserApi
import org.openapitools.client.models.User
import org.openapitools.client.models.UserRegister

class UserApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserApi
        //val apiInstance = UserApi()

        // to test userUserIdGet
        should("test userUserIdGet") {
            // uncomment below to test userUserIdGet
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val result : User = apiInstance.userUserIdGet(userId)
            //result shouldBe ("TODO")
        }

        // to test userUserIdPatch
        should("test userUserIdPatch") {
            // uncomment below to test userUserIdPatch
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val userRegister : UserRegister =  // UserRegister | 
            //val result : User = apiInstance.userUserIdPatch(userId, userRegister)
            //result shouldBe ("TODO")
        }

    }
}
