/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.FutureMeets
import org.openapitools.client.models.FutureMeet
import org.openapitools.client.models.HistoryMeet

class FutureMeetsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FutureMeets
        //val modelInstance = FutureMeets()

        // to test the property `notApproved`
        should("test notApproved") {
            // uncomment below to test the property
            //modelInstance.notApproved shouldBe ("TODO")
        }

        // to test the property `approved`
        should("test approved") {
            // uncomment below to test the property
            //modelInstance.approved shouldBe ("TODO")
        }

    }
}
