/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.FutureMeetNotApproved

class FutureMeetNotApprovedTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FutureMeetNotApproved
        //val modelInstance = FutureMeetNotApproved()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `slot`
        should("test slot") {
            // uncomment below to test the property
            //modelInstance.slot shouldBe ("TODO")
        }

    }
}
