/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.UserScheduleChange
import org.openapitools.client.models.ScheduleSlot

class UserScheduleChangeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserScheduleChange
        //val modelInstance = UserScheduleChange()

        // to test the property `toDelete`
        should("test toDelete") {
            // uncomment below to test the property
            //modelInstance.toDelete shouldBe ("TODO")
        }

        // to test the property `toAdd`
        should("test toAdd") {
            // uncomment below to test the property
            //modelInstance.toAdd shouldBe ("TODO")
        }

    }
}
