/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.UserRegister

class UserRegisterTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserRegister
        //val modelInstance = UserRegister()

        // to test the property `login`
        should("test login") {
            // uncomment below to test the property
            //modelInstance.login shouldBe ("TODO")
        }

        // to test the property `password`
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

        // to test the property `tgHandle`
        should("test tgHandle") {
            // uncomment below to test the property
            //modelInstance.tgHandle shouldBe ("TODO")
        }

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `tosAccept`
        should("test tosAccept") {
            // uncomment below to test the property
            //modelInstance.tosAccept shouldBe ("TODO")
        }

    }
}
