services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      -  ${DB_PORT}:5432
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d